Use azure linux for Image Builder container image
dotnet/docker-tools pull request #1393
Opened 2024-08-12 23:29 UTC by ellahathaway

Things to note:
1. Because there are no distroless azure linux sdk images and the goal is ultimately to make this a distroless image, I chose to use the full azure linux image from runtime rather than the full azure linux image from sdk.
2. Because this is a runtime image, I had to install the dotnet sdk in order for the `dotnet publish` command to work.
3. There were some weird issues with the docker api version when I ran ImageBuilder in CI. I found the setting the ENV variable explicitly was the best fix. I'm looking into other solutions.

[Test build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2513972&view=results) (internal Microsoft link)

2024-08-13 14:13 UTC, MichaelSimons commented on src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
> +FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/runtime:9.0-preview-azurelinux3.0 AS build-env
I don't think we should be using 9.0 during previews.  Perhaps once it reaches RC, but not before.

2024-08-13 14:21 UTC, mthalman commented on src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
> +FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/runtime:9.0-preview-azurelinux3.0 AS build-env
> Because there are no distroless azure linux sdk images and the goal is ultimately to make this a distroless image, I chose to use the full azure linux image from runtime rather than the full azure linux image from sdk.

The ultimate goal is to use a distroless image for the _final_ image. We can use whatever we need for the intermediate stages, such as this one. So we should continue to use the `sdk` image for this stage.

2024-08-13 14:21 UTC, mthalman commented on src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
> +    git \
```suggestion
      moby-engine \
      moby-cli \
      moby-buildx \
      git \
```

2024-08-13 14:21 UTC, mthalman commented on src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
> +ENV DOCKER_API_VERSION=1.43
> There were some weird issues with the docker api version when I ran ImageBuilder in CI. I found the setting the ENV variable explicitly was the best fix. I'm looking into other solutions/seeing if this is even still needed after installing another necessary package.

If this is still necessary, it'd be good to document more about the need for it. What is the original issue that prompted the need for it? Why does this resolve it?

2024-08-13 14:23 UTC, lbussell reviewed
We should block this on https://github.com/dotnet/dotnet-docker/issues/5467, which should be completed today or tomorrow. Then, you'll be able to use the non-nightly images.

2024-08-13 14:23 UTC, lbussell commented on src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
> +
It's expected to use the non-distroless SDK image, even with a distroless Runtime image, since the only outputs from the SDK build layer are DLLs/executables. You can see our [sample distroless Ubuntu Dockerfile](https://github.com/dotnet/dotnet-docker/blob/248742f8a701def93947ec1d2acdbccc4540170d/samples/aspnetapp/Dockerfile.chiseled) for reference. The images you most likely want to use for testing are:

- `mcr.microsoft.com/dotnet/nightly/sdk:8.0-azurelinux3.0`
- `mcr.microsoft.com/dotnet/nightly/runtime:8.0-azurelinux3.0`

2024-08-13 16:45 UTC, ellahathaway commented on src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
> +ENV DOCKER_API_VERSION=1.43
This was something that came up when I was running the image builder image locally while trying to investigate failures in CI; the error message was complaining about the API version being too low (CI just showed red but didn't display this particular error). Turns out this local error was just a red herring because when I installed another moby package, the errors resolved in CI.

2024-08-13 16:51 UTC, ellahathaway commented on src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
> +FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/runtime:9.0-preview-azurelinux3.0 AS build-env
I didn't see any azure linux images in main except for the 9.0-preview ones, so that's what led me to using those. But I see now that the non-preview images are in nightly and are expected to be added to main with https://github.com/dotnet/dotnet-docker/pull/5789. For now, I'll use the 8.0 nightly images and then switch to main once that PR gets merged.

2024-08-14 21:13 UTC, lbussell requested changes

2024-08-14 21:13 UTC, lbussell commented on src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
> +      tar \
`tar` is installed by default in the SDK image:

https://github.com/dotnet/dotnet-docker/blob/a46d52ee1798fb37e050f52ca3fc802455ca229d/src/sdk/8.0/azurelinux3.0/amd64/Dockerfile#L18-L22

2024-08-14 21:13 UTC, lbussell commented on src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
> +    && curl -sSL https://github.com/oras-project/oras/releases/download/v${oras_version}/oras_${oras_version}_linux_${TARGETARCH}.tar.gz -o oras_linux.tar.gz \
What's the reasoning for using `-sSL` instead of `-fSL` like our other images? https://github.com/dotnet/dotnet-docker/blob/a46d52ee1798fb37e050f52ca3fc802455ca229d/src/sdk/8.0/azurelinux3.0/amd64/Dockerfile#L25

2024-08-14 21:13 UTC, lbussell commented on src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
> +RUN dotnet restore -r linux-$TARGETARCH ./src/Microsoft.DotNet.ImageBuilder.csproj
```suggestion
RUN dotnet restore -a $TARGETARCH ./src/Microsoft.DotNet.ImageBuilder.csproj
```

2024-08-14 21:13 UTC, lbussell commented on src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
> +RUN dotnet publish -r linux-$TARGETARCH ./src/Microsoft.DotNet.ImageBuilder.csproj --self-contained=true --no-restore -o out
```suggestion
RUN dotnet publish -a $TARGETARCH ./src/Microsoft.DotNet.ImageBuilder.csproj --self-contained=true --no-restore -o out
```

2024-08-14 21:13 UTC, lbussell commented on src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
> +      moby-buildx \
Please use `docker-*` versions where available. These packages were renamed: https://github.com/microsoft/azurelinux/blob/3.0/SPECS/docker-cli/docker-cli.spec

```
PS> docker run -it --rm mcr.microsoft.com/dotnet/sdk:8.0-azurelinux3.0 tdnf search docker
...
docker-buildx : A Docker CLI plugin for extended build capabilities with BuildKit
docker-cli : The open-source application container engine client.
moby-engine : The open-source application container engine
```

2024-08-14 21:57 UTC, ellahathaway commented on src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
> +    && curl -sSL https://github.com/oras-project/oras/releases/download/v${oras_version}/oras_${oras_version}_linux_${TARGETARCH}.tar.gz -o oras_linux.tar.gz \
No reasoning - I'm just familiar with -sSL and didn't realize that we use -fSL in other areas. I'll update my PR with -fSL.

2024-08-14 22:02 UTC, ellahathaway commented on src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
> +      moby-buildx \
Will do - looks like I can replace `moby-cli` and `moby-buildx`.

2024-08-14 22:04 UTC, ellahathaway commented on src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
> +RUN dotnet publish -r linux-$TARGETARCH ./src/Microsoft.DotNet.ImageBuilder.csproj --self-contained=true --no-restore -o out
```
=> ERROR [build-env 8/9] RUN dotnet publish -a amd64 ./src/Microsoft.DotNet.ImageBuilder.csproj --self-contained=true --no-restore -o out                                                                       1.8s
------
 > [build-env 8/9] RUN dotnet publish -a amd64 ./src/Microsoft.DotNet.ImageBuilder.csproj --self-contained=true --no-restore -o out:
1.707 /usr/share/dotnet/sdk/8.0.400/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(491,5): error NETSDK1112: The runtime pack for Microsoft.NETCore.App.Runtime.linux-x64 was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'linux-x64'. [/image-builder/src/Microsoft.DotNet.ImageBuilder.csproj]
```

Looks like the runtime identifier is required.

2024-08-14 22:08 UTC, ellahathaway commented on src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux
> +RUN dotnet restore -r linux-$TARGETARCH ./src/Microsoft.DotNet.ImageBuilder.csproj
See https://github.com/dotnet/docker-tools/pull/1393#discussion_r1717600858

2024-08-15 12:41 UTC, mthalman approved these changes

2024-08-15 15:59 UTC, lbussell approved these changes

2024-08-15 17:35 UTC, merged